import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Sawant Sites",
    template: "%s Sawant sites",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header
          style={{
            backgroundColor: "#f9f9f9",
            padding: "16px",
            boxShadow: "0px 2px 4px rgba(0, 0, 0, 0.1)",
            position: "fixed",
            top: 0,
            left: 0,
            right: 0,
            zIndex: 1000,
          }}
        >
          <p className="text-black">this is a header</p>
        </header>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
        </main>
        <footer
          style={{
            backgroundColor: "#f9f9f9",
            padding: "16px",
            boxShadow: "0px 2px 4px rgba(0, 0, 0, 0.1)",
            position: "fixed",
            bottom: 0,
            left: 0,
            right: 0,
            zIndex: 1000,
            marginTop: "64px",
          }}
        >
          <p className="text-black">this is a footer</p>
        </footer>
      </body>
    </html>
  );
}
